#Q1 Find the top 10 transactions with the highest transaction amount.
select TransactionID, AccountID, TransactionAmount
from bank_transaction_clean
order by TransactionAmount desc 
limit 10;


#Q2 Find the transaction types that have more than 500 transactions.
select TransactionType, count(*) as transaction_count
from bank_transaction_clean
group by TransactionType
having count(*) > 500;


#Q3 Find the location with the highest total transaction value.
select Location, round(sum(TransactionAmount),2) as total_transaction_amt
from bank_transaction_clean
group by Location
order by total_transaction_amt desc
limit 1;


#Q4 Find the location with the highest number of transactions.
select Location, count(TransactionID) as transaction_count
from bank_transaction_clean
group by Location
order by transaction_count desc
limit 1;



#Q5 Find the occupation with the highest average transaction amount.
select CustomerOccupation, round(avg(TransactionAmount),2) as avg_transaction_amt
from bank_transaction_clean
group by CustomerOccupation
order by avg_transaction_amt desc
limit 1;


#Q6 Find the channel with the highest total transaction value.
select `Channel`, round(sum(TransactionAmount),2) as total_transaction_amt
from bank_transaction_clean
group by `Channel`
order by total_transaction_amt desc
limit 1;


#Q7 Find the top 10 accounts based on total transaction value.
#Important: this means total value generated by an account, not its single biggest transaction.
select AccountID, round(sum(TransactionAmount),2) as total_transaction_amt
from bank_transaction_clean
group by AccountID
order by total_transaction_amt desc
limit 10;

#Q8 Find the top 10 accounts based on number of transactions.
#This measures activity, not transaction value.
select AccountID, count(TransactionID) as number_of_transactions
from bank_transaction_clean
group by AccountID
order by number_of_transactions desc
limit 10;

#Q9 Find the transaction type with the highest average transaction amount.
select TransactionType, round(avg(TransactionAmount),2) as avg_transaction_amt
from bank_transaction_clean
group by TransactionType
order by avg_transaction_amt desc
limit 1;


#Q10 Find the occupation with the highest average account balance.
select CustomerOccupation, round(avg(AccountBalance),2)as avg_acct_balance
from bank_transaction_clean
group by CustomerOccupation
order by avg_acct_balance desc
limit 1;

#Q11 — Age-group transaction analysis, 
#Then find the number of transactions in each age group.
select case
	   when CustomerAge < 25 then '18-24'
       when CustomerAge between 25 and 34 then '25-34'
       when CustomerAge between 35 and 44 then '35-44'
       when CustomerAge between 45 and 54 then '45-54'
       else '55+'
       end as age_groups,
       count(*) as transaction_count
	   from bank_transaction_clean
       group by  age_groups
       order by transaction_count desc;
       
#Q12 — Average transaction by age group Using the same age groups, 
#find the average transaction amount for each age group.

select case 
	   when CustomerAge < 25 then '18-24'
       when CustomerAge between 25 and 34 then '25-34'
       when CustomerAge between 35 and 44 then '35-44'
       when CustomerAge between 45 and 54 then '45-54'
       else '55+'
       end as age_groups,
       round(avg(TransactionAmount),2) as avg_transaction_amt
       from bank_transaction_clean
       group by age_groups
       order by avg_transaction_amt desc;
       
#Q13 — Transaction amount classification
#Find how many transactions fall into each category.
select case 
		when TransactionAmount < 1000 then 'Low'
        when TransactionAmount between 1000 and 5000 then 'Medium'
        when TransactionAmount > 5000 then 'High'
        end as Categorys,
        count(*) as transaction_amt_count
        from bank_transaction_clean
        group by Categorys
        order by transaction_amt_count desc;
        
#Q14 — High-value transaction percentage
#Find the percentage of transactions that are above 
#the overall average transaction amount.
select round(count(*) * 100 / (select count(*) from bank_transaction_clean),2) as percentage_above_avg
from  bank_transaction_clean
where TransactionAmount > (
select round(avg(TransactionAmount),2) as overall_avg_transaction_amt
from bank_transaction_clean b2);



#Q15 — Account balance classification
#Find the number of accounts/records in each balance category.

select case
		when AccountBalance < 10000 then 'Low Balance'
        when AccountBalance between 10000 and 50000 then 'Medium Balance'
        when AccountBalance > 50000 then 'High Balance'
        end as acct_bal_classifiaction,
        count(AccountBalance) as acct_bal_count
		from bank_transaction_clean
        group by acct_bal_classifiaction
        order by acct_bal_count desc;

#Q16 — Login attempt risk classification
#Find the number of transactions in each risk category.

select case
		when LoginAttempts between 1 and 2 then 'Low Risk'
        when LoginAttempts = 3 then 'Medium Risk'
        when LoginAttempts >= 4 then 'High Risk'
        end as login_attempt_risk,
        count(TransactionID) as transaction_count
from bank_transaction_clean
group by login_attempt_risk
order by transaction_count desc;

#Q17 — High-value + high-login transactions
select TransactionID, AccountID, TransactionAmount, LoginAttempts
from bank_transaction_clean
where TransactionAmount > (
							select round(avg(TransactionAmount),2) as overall_avg_transaction_amt
							from bank_transaction_clean)
			and LoginAttempts > (
							select round(avg(LoginAttempts),2)as overall_avg_login_attempts
							from bank_transaction_clean)
							order by TransactionAmount desc;
                            
#Q18 — Occupation performance Find occupations where:
#the average transaction amount is greater
#than the overall average transaction amount.
select CustomerOccupation, round(avg(TransactionAmount),2) as avg_transaction_amt
from bank_transaction_clean
group by CustomerOccupation
having round(avg(TransactionAmount),2) > (
											select round(avg(TransactionAmount),2) as overall_avg_transaction_amt
											from bank_transaction_clean);

#Q19 — Most active account
#Find the account that has made the highest number of transactions.
select AccountID, count(TransactionAmount) as transaction_count
from bank_transaction_clean
group by AccountID
order by transaction_count desc
limit 1;

#Q20 — Highest-value account
#Find the account with the highest total transaction value.
select AccountID, round(sum(TransactionAmount),2) as total_transaction_value
from bank_transaction_clean
group by AccountID
order by total_transaction_value desc
limit 1;

#Q21 — Transactions above the average
#Find all transactions where the transaction amount is greater than 
#the overall average transaction amount.
select  TransactionID, AccountID, TransactionAmount
from bank_transaction_clean
where TransactionAmount > (
select round(avg(TransactionAmount),2) as overall_avg_transaction_amt
from bank_transaction_clean);


#Q22 — Accounts above average transaction value
#Find accounts whose total transaction value is greater than 
#the average total transaction value across all accounts.
select AccountID, round(sum(TransactionAmount),2) as total_transaction_value
from bank_transaction_clean
group by AccountID
having sum(TransactionAmount) > (
select avg(total_trans_amt) as avg_total_trans_value from (
select AccountID, round(sum(TransactionAmount),2) as total_trans_amt  
from bank_transaction_clean
group by AccountID) x);


#Q23 — Occupations above overall average
#Find occupations whose average transaction amount is greater than 
#the overall average transaction amount.
select CustomerOccupation, round(avg(TransactionAmount),2) as occpt_avg_trans_amt
from bank_transaction_clean
group by CustomerOccupation
having round(avg(TransactionAmount),2) > (
select round(avg(TransactionAmount),2) as overall_avg_transaction_amt 
from bank_transaction_clean);

#Q24 — Highest transaction
#Find the transaction(s) whose transaction amount equals 
#the maximum transaction amount in the entire dataset.
select TransactionID, AccountID, TransactionAmount
from bank_transaction_clean
where TransactionAmount = (
select max(TransactionAmount) as max_transaction_amt 
from bank_transaction_clean);


#Q25 — Accounts with more transactions than the average account
#Find accounts whose transaction count is greater than 
#the average number of transactions per account.
select AccountID, count(*) as acct_transaction_cnt
from bank_transaction_clean
group by AccountID
having count(*)  > (
select avg(cnt_of_transactions) as avg_no_of_trans_per_acct from (
select count(TransactionID) as cnt_of_transactions
from bank_transaction_clean
group by AccountID)k);


#Q26 — Transactions from the highest-value account
#First identify the account with the highest total transaction value.
#Then return all transactions belonging to that account.
select AccountID, TransactionID, TransactionAmount
from bank_transaction_clean
where AccountID = (
select max(total_transaction_amt) from (
select round(sum(TransactionAmount),2) as total_transaction_amt
from bank_transaction_clean
group by AccountID)x);


#Q27 — Transactions above their transaction-type average
#For every transaction, find transactions whose amount is greater than 
#the average transaction amount for their own transaction type.
select b1.TransactionID, b1.TransactionType, b1.TransactionAmount, d.avg_transaction_amt_by_grp
from bank_transaction_clean b1
join (
select TransactionType, round(avg(TransactionAmount),2)as avg_transaction_amt_by_grp
from bank_transaction_clean 
group by TransactionType) d on b1.TransactionType = d.TransactionType
where b1.TransactionAmount > d.avg_transaction_amt_by_grp;


#Q28 — Highest-average transaction type
#Find the transaction type whose average transaction amount is 
#the highest among all transaction types.
select TransactionType, round(avg(TransactionAmount),2)as avg_transaction_amt_by_grp
from bank_transaction_clean
group by TransactionType 
having round(avg(TransactionAmount),2)= (
select max(avg_transaction_amt_by_grp) from 
(select TransactionType, round(avg(TransactionAmount),2)as avg_transaction_amt_by_grp
from bank_transaction_clean
group by TransactionType)z);


#Q29 — Locations above average transaction value
#Find locations whose total transaction value is greater than 
#the average total transaction value across all locations.
select Location, round(sum(TransactionAmount),2)as total_transaction_value
from bank_transaction_clean
group by Location
having round(sum(TransactionAmount),2) > (
select round(avg(total_transaction_value),2)as avg_total_transaction_value 
from (
select round(sum(TransactionAmount),2)as total_transaction_value
from bank_transaction_clean
group by Location)x); 


#Q30 — High-value accounts
#Find accounts whose total transaction value is greater than 
#the overall average account transaction value.
select AccountID, round(sum(TransactionAmount),2)as total_transaction_value
from bank_transaction_clean
group by AccountID
having round(sum(TransactionAmount),2) > (
select round(avg(total_transaction_value),2) as overall_avg_acct_trans_value from (
select  round(sum(TransactionAmount),2) as total_transaction_value
from bank_transaction_clean
group by AccountID)c);




#Q31 — Account transaction totals
#Create a CTE called account_totals that calculates:
#AccountID
#total transaction value for each account
#Then use that CTE to find the top 10 accounts by total transaction value.

with account_totals as (
select AccountID, round(sum(TransactionAmount),2) as total_transaction_value
from bank_transaction_clean
group by AccountID
)
select AccountID, total_transaction_value
from account_totals
order by total_transaction_value desc 
limit 10;

#Q32 — Accounts above average
#Using a CTE, find accounts whose total transaction value is greater than 
#the average total transaction value across all accounts.

with accounts_above_avg as(
select AccountID, round(sum(TransactionAmount),2)as total_transaction_value
from bank_transaction_clean 
group by AccountID)
select AccountID, total_transaction_value
from accounts_above_avg 
where total_transaction_value > (select avg(total_transaction_value) 
								 from accounts_above_avg);
                                 
#Q33 — Most active accounts
#Using a CTE, calculate the number of transactions for each account.
#Then find the top 10 most active accounts.

with most_active_account as (
select AccountID, count(TransactionID)as transaction_cnt
from bank_transaction_clean
group by AccountID)
select AccountID, transaction_cnt
from most_active_account 
order by transaction_cnt desc
limit 10;


#Q34 — Location performance
#Using a CTE, calculate the total transaction value for each location.
#Then find locations whose total transaction value is above the average location transaction value.

with location_performance as(
select Location, round(sum(TransactionAmount),2)as total_transaction_value
from bank_transaction_clean
group by Location)
select Location, total_transaction_value
from location_performance
where total_transaction_value > (select avg(total_transaction_value) 
								 from location_performance);
                                 

#Q35 — Transaction type performance
#Using a CTE, calculate the average transaction amount for each TransactionType.
#Then return the transaction type(s) with the highest average transaction amount.

with transaction_type_perf as (
select 	
		TransactionType, 
        avg(TransactionAmount) as avg_transaction_amt
from bank_transaction_clean
group by TransactionType
)
select TransactionType , round(avg_transaction_amt,2)as avg_transaction_amt
from transaction_type_perf 
where avg_transaction_amt =(select max(avg_transaction_amt)
							from transaction_type_perf);
                            
                            
#Q36 — Account total beside every transaction
select TransactionID, AccountID, TransactionAmount,
round(sum(TransactionAmount) over(partition by AccountID),2)as total_transaction_value
from bank_transaction_clean;


#Q37 — Rank transactions within each account
#For every transaction, assign a rank based on TransactionAmount, 
#with the highest transaction receiving rank 1 within each account.

select TransactionID, AccountID, TransactionAmount,
rank() over(partition by AccountID order by TransactionAmount desc)as transaction_ranks
from bank_transaction_clean;


#Q38 — Highest transaction for each account
#Using a window function, 
#find the highest-value transaction for every account. 
#If you rank transactions within each account, what rank represents the highest transaction?
select TransactionID, AccountID, TransactionAmount,transactions_rank
from (
select TransactionID, AccountID, TransactionAmount,
rank() over(partition by AccountID order by TransactionAmount desc)as transactions_rank
from bank_transaction_clean)w 
where w.transactions_rank = 1;
# 1 is the rank representing highest transaction because we are ordering the transaction amount/value in descnding ording to get highest value 

#Q39 — Top 3 transactions per account
#Find the top 3 highest-value transactions for every account.
select TransactionID, AccountID, TransactionAmount,transaction_ranks 
from (
select TransactionID, AccountID, TransactionAmount,
rank() over(partition by AccountID order by TransactionAmount desc) as transaction_ranks
from bank_transaction_clean)t 
where t.transaction_ranks <= 3;

#Q40 — Transaction type average beside every transaction
select TransactionID, TransactionType, TransactionAmount,
round(avg(TransactionAmount) over(partition by TransactionType),2) as avg_trasnaction_by_type
from bank_transaction_clean;


#Q41 — ROW_NUMBER
#For every account, assign a unique row number to its transactions based on highest transaction amt

select TransactionID, AccountID, TransactionAmount,
row_number() over(partition by AccountID order by TransactionAmount desc)as row_num
from bank_transaction_clean;

#Q42 — Difference between RANK and DENSE_RANK
#Order by account and transaction amount descending.

select TransactionID, AccountID, TransactionAmount,
rank() over(partition by AccountID order by TransactionAmount desc) as rank_assigned,
dense_rank() over(partition by AccountID  order by TransactionAmount desc) as dense_rank_assigned
from bank_transaction_clean;

#Q43 — Second-highest transaction per account
#Find the second-highest transaction amount for every account.

with second_highest_transaction as(
select TransactionID, AccountID, TransactionAmount,
dense_rank() over(partition by AccountID order by TransactionAmount desc) as dense_rank_assigned
from bank_transaction_clean)
select * 
from second_highest_transaction
where second_highest_transaction.dense_rank_assigned = 2;


#Q44 — Top 2 transaction types by average amount
#Calculate the average transaction amount for each TransactionType, 
#then rank the transaction types by their average amount.
with cte as (
select TransactionType, round(avg(TransactionAmount),2) as type_avg
from bank_transaction_clean
group by TransactionType
),
ranked_avg_type as(
select TransactionType, type_avg,
rank() over(order by type_avg desc) as rank_assigned
from cte)
select TransactionType, type_avg, rank_assigned
from ranked_avg_type
where rank_assigned <= 2;

#Q45 — Account's largest transaction vs account total
#total transaction value of the account
#the percentage that this transaction contributes to the account's total

select TransactionID, AccountID, TransactionAmount,
round(sum(TransactionAmount) over(partition by AccountID),2) as total_transaction_value,
round((TransactionAmount/round(sum(TransactionAmount) over(partition by AccountID),2)),2) * 100 as percentage_contribution
from bank_transaction_clean;


#Q46 — Running transaction total
#For each account, calculate a running total of transaction amount, ordered by TransactionID.

select TransactionID, AccountID, TransactionAmount,
sum(TransactionAmount) over(partition by AccountID order by TransactionID) as running_total
from bank_transaction_clean;


#Q47 — Previous transaction amount
#For every transaction, show the previous transaction amount for the same account.

select TransactionID, AccountID, TransactionAmount,
lag(TransactionAmount) over(partition by AccountID order by TransactionID) as previous_transaction_amt
from bank_transaction_clean;


#Q48 — Difference from previous transaction
#For every transaction, calculate:
#Current transaction amount − previous transaction amount
with transaction_comparission as (
select TransactionID, AccountID, TransactionAmount,
lag(TransactionAmount) over(partition by AccountID order by TransactionID) as previous_transaction_amount,
(TransactionAmount - lag(TransactionAmount) over(partition by AccountID order by TransactionID)) as amount_difference
from bank_transaction_clean)
select TransactionID, AccountID, TransactionAmount,previous_transaction_amount,
TransactionAmount - previous_transaction_amount as  amount_difference
from transaction_comparission;


#Q49 — Transaction amount compared with account average
#average transaction amount for that account
#whether the transaction is Above Average or Below/Equal Average

with transaction_comparrision as(
select TransactionID, AccountID, TransactionAmount,
avg(TransactionAmount) over(partition by AccountID) as avg_transaction_amount
from bank_transaction_clean)
select TransactionID, AccountID, TransactionAmount,
round((avg_transaction_amount),2) as avg_transaction_amount,
case 
	when TransactionAmount > avg_transaction_amount then 'Above Average'
    when TransactionAmount < avg_transaction_amount then 'Below Average'
    else 'Equal Average'
    end as Amount_Classification
from transaction_comparrision;


#Q50 — Highest transaction per transaction type
#For each TransactionType, find the highest-value transaction.
with highest_transaction_per_type as (
select TransactionID, TransactionType, TransactionAmount,
dense_rank() over(partition by TransactionType order by TransactionAmount desc) as ranks_assigned
from bank_transaction_clean)
select * 
from highest_transaction_per_type
where ranks_assigned = 1;


#Mixed Interview/Business Questions
#Find the top 3 accounts with the highest total transaction value, 
#but return all accounts tied at 3rd place.
with cte as (
select AccountID, round(sum(TransactionAmount),2) as total_transaction_value
from bank_transaction_clean
group by AccountID
),
ranked_cte as(
select AccountID, total_transaction_value,
dense_rank() over(order by total_transaction_value desc) as ranks
from cte
)
select AccountID, total_transaction_value,ranks
from ranked_cte
where ranks = 3;


#Q52
#Find transactions that are above their account's average transaction amount.

with cte as(
select TransactionID, AccountID, TransactionAmount, 
avg(TransactionAmount) over(partition by AccountID) as avg_transaction_amt
from bank_transaction_clean)
select TransactionID, AccountID, TransactionAmount, 
round(avg_transaction_amt,2) avg_transaction_amt
from cte
where TransactionAmount > avg_transaction_amt;


#Q53
#Find the most active account in each location.

select distinct Location, count(*)
from bank_transaction_clean
group by Location;

#Q54
#Find the highest-value transaction for each occupation.
with cte as (
select CustomerOccupation, TransactionAmount,
dense_rank() over(partition by CustomerOccupation order by TransactionAmount desc)as ranks
from bank_transaction_clean)
select *
from cte 
where ranks = 1;


#Q55
#Find accounts where the latest transaction is higher than 
#the account's average transaction amount.
with cte1 as (
select AccountID, TransactionAmount, TransactionDate, 
avg(TransactionAmount) over(partition by AccountID) as avg_amt,
dense_rank() over(partition by AccountID order by TransactionDate desc) as ranks
from bank_transaction_clean),
cte2 as (
select *
from cte1 
where ranks = 1)
select AccountID, TransactionAmount, TransactionDate, round(avg_amt,2) as avg_amt, ranks
from cte2 
where TransactionAmount > avg_amt;


#Q56
#Find the top 3 transaction types by total transaction value.

select TransactionType, round(sum(TransactionAmount),2) as total_transaction_value
from bank_transaction_clean
group by TransactionType
order by total_transaction_value desc
limit 3;


#Q57
#Find each account's percentage contribution to 
#the total transaction value of the entire dataset.

select AccountID, TransactionAmount, round(sum(TransactionAmount) over(),2) as total_transaction_value,
round((TransactionAmount / sum(TransactionAmount) over())*100,2)as amt_contribution
from bank_transaction_clean;


SELECT COUNT(*) AS total_rows
FROM bank_transaction_clean;

SELECT TransactionID, COUNT(*) AS duplicate_count
FROM bank_transaction_clean
GROUP BY TransactionID
HAVING COUNT(*) > 1;

SELECT
    COUNT(*) AS total_rows,
    SUM(TransactionID IS NULL) AS null_transaction_id,
    SUM(AccountID IS NULL) AS null_account_id,
    SUM(TransactionAmount IS NULL) AS null_transaction_amount,
    SUM(CustomerAge IS NULL) AS null_customer_age,
    SUM(Location IS NULL) AS null_location,
    SUM(TransactionType IS NULL) AS null_transaction_type
FROM bank_transaction_clean;

SELECT *
FROM bank_transaction_clean
WHERE TransactionAmount < 0;

SELECT *
FROM bank_transaction_clean
WHERE CustomerAge < 18
   OR CustomerAge > 100;
   
   SELECT *
FROM bank_transaction_clean
WHERE LoginAttempts < 0;

SELECT *
FROM bank_transaction_clean
WHERE TransactionDuration < 0;

SELECT
    TransactionID,
    AccountID,
    TransactionAmount
FROM bank_transaction_clean
ORDER BY TransactionAmount DESC
LIMIT 10;

SELECT
    TransactionType,
    COUNT(*) AS transaction_count,
    ROUND(SUM(TransactionAmount), 2) AS total_transaction_value,
    ROUND(AVG(TransactionAmount), 2) AS average_transaction_amount
FROM bank_transaction_clean
GROUP BY TransactionType
ORDER BY total_transaction_value DESC;

SELECT
    Channel,
    COUNT(*) AS transaction_count,
    ROUND(SUM(TransactionAmount), 2) AS total_transaction_value,
    ROUND(AVG(TransactionAmount), 2) AS average_transaction_amount
FROM bank_transaction_clean
GROUP BY Channel
ORDER BY total_transaction_value DESC;

SELECT
    AccountID,
    ROUND(SUM(TransactionAmount), 2) AS total_transaction_value
FROM bank_transaction_clean
GROUP BY AccountID
ORDER BY total_transaction_value DESC
LIMIT 10;

SELECT
    AccountID,
    COUNT(TransactionID) AS transaction_count
FROM bank_transaction_clean
GROUP BY AccountID
ORDER BY transaction_count DESC
LIMIT 10;

WITH account_totals AS (
    SELECT
        AccountID,
        SUM(TransactionAmount) AS total_transaction_value
    FROM bank_transaction_clean
    GROUP BY AccountID
)
SELECT
    AccountID,
    ROUND(total_transaction_value, 2) AS total_transaction_value
FROM account_totals
WHERE total_transaction_value > (
    SELECT AVG(total_transaction_value)
    FROM account_totals
)
ORDER BY total_transaction_value DESC;

SELECT
    CustomerOccupation,
    COUNT(*) AS transaction_count,
    ROUND(SUM(TransactionAmount), 2) AS total_transaction_value,
    ROUND(AVG(TransactionAmount), 2) AS average_transaction_amount,
    ROUND(AVG(AccountBalance), 2) AS average_account_balance
FROM bank_transaction_clean
GROUP BY CustomerOccupation
ORDER BY total_transaction_value DESC;

SELECT
    CASE
        WHEN CustomerAge < 25 THEN '18-24'
        WHEN CustomerAge BETWEEN 25 AND 34 THEN '25-34'
        WHEN CustomerAge BETWEEN 35 AND 44 THEN '35-44'
        WHEN CustomerAge BETWEEN 45 AND 54 THEN '45-54'
        ELSE '55+'
    END AS age_group,
    COUNT(*) AS transaction_count,
    ROUND(SUM(TransactionAmount), 2) AS total_transaction_value,
    ROUND(AVG(TransactionAmount), 2) AS average_transaction_amount
FROM bank_transaction_clean
GROUP BY age_group
ORDER BY total_transaction_value DESC;

SELECT
    Location,
    COUNT(*) AS transaction_count,
    ROUND(SUM(TransactionAmount), 2) AS total_transaction_value,
    ROUND(AVG(TransactionAmount), 2) AS average_transaction_amount
FROM bank_transaction_clean
GROUP BY Location
ORDER BY total_transaction_value DESC;


WITH ranked_transactions AS (
    SELECT
        TransactionID,
        AccountID,
        TransactionAmount,
        RANK() OVER (
            PARTITION BY AccountID
            ORDER BY TransactionAmount DESC
        ) AS transaction_rank
    FROM bank_transaction_clean
)
SELECT
    AccountID,
    TransactionID,
    TransactionAmount
FROM ranked_transactions
WHERE transaction_rank = 1;

WITH account_analysis AS (
    SELECT
        TransactionID,
        AccountID,
        TransactionAmount,
        AVG(TransactionAmount) OVER (
            PARTITION BY AccountID
        ) AS account_average
    FROM bank_transaction_clean
)
SELECT
    TransactionID,
    AccountID,
    TransactionAmount,
    ROUND(account_average, 2) AS account_average
FROM account_analysis
WHERE TransactionAmount > account_average
ORDER BY TransactionAmount DESC;

WITH account_activity AS (
    SELECT
        Location,
        AccountID,
        COUNT(*) AS transaction_count
    FROM bank_transaction_clean
    GROUP BY Location, AccountID
),
ranked_accounts AS (
    SELECT
        Location,
        AccountID,
        transaction_count,
        RANK() OVER (
            PARTITION BY Location
            ORDER BY transaction_count DESC
        ) AS account_rank
    FROM account_activity
)
SELECT
    Location,
    AccountID,
    transaction_count
FROM ranked_accounts
WHERE account_rank = 1;

WITH transaction_analysis AS (
    SELECT
        TransactionID,
        AccountID,
        TransactionAmount,
        LoginAttempts,
        AVG(TransactionAmount) OVER (
            PARTITION BY AccountID
        ) AS account_avg_transaction
    FROM bank_transaction_clean
)
SELECT
    TransactionID,
    AccountID,
    TransactionAmount,
    LoginAttempts
FROM transaction_analysis
WHERE TransactionAmount > account_avg_transaction
  AND LoginAttempts > (
      SELECT AVG(LoginAttempts)
      FROM bank_transaction_clean
  )
ORDER BY TransactionAmount DESC;


WITH account_totals AS (
    SELECT
        AccountID,
        SUM(TransactionAmount) AS account_total
    FROM bank_transaction_clean
    GROUP BY AccountID
)
SELECT
    AccountID,
    ROUND(account_total, 2) AS account_total,
    ROUND(
        account_total * 100 /
        SUM(account_total) OVER (),
        2
    ) AS percentage_of_total
FROM account_totals
ORDER BY percentage_of_total DESC;

SELECT
    CASE
        WHEN TransactionAmount < 1000 THEN 'Low'
        WHEN TransactionAmount BETWEEN 1000 AND 5000 THEN 'Medium'
        ELSE 'High'
    END AS transaction_category,
    COUNT(*) AS transaction_count,
    ROUND(SUM(TransactionAmount), 2) AS total_transaction_value,
    ROUND(AVG(TransactionAmount), 2) AS average_transaction_amount
FROM bank_transaction_clean
GROUP BY transaction_category
ORDER BY total_transaction_value DESC;
