
## Exploratory Data Analysis [EDA]
# total transactions
select count(*) as total_transactions from bank_transaction_clean;

# total transaction value
select sum(TransactionAmount)as total_amount from bank_transaction_clean;

# average transaction value
select avg(TransactionAmount)as avg_amount from bank_transaction_clean;

# highest transaction amount
select max(TransactionAmount) as max_transaction_amount from bank_transaction_clean;

# lowest transaction amount
select min(TransactionAmount) as min_transaction_amount from bank_transaction_clean;

# customer behaviour (total transaction value from each city)
select Location, round(sum(TransactionAmount), 2) as total_value
from bank_transaction_clean
group by Location;
 
# most commonly used transaction type
select TransactionType ,count(*)as most_commonly_preffered
from bank_transaction_clean
group by TransactionType;

# what customer age has the longest transaction duration
select CustomerAge, max(TransactionDuration) as longest_transaction_duration
from bank_transaction_clean
group by CustomerAge
order by longest_transaction_duration desc;


# avgerage transaction amount based on customers occupation
select CustomerOccupation, round(avg(TransactionAmount),2) as average_transaction_amount 
from bank_transaction_clean
group by CustomerOccupation;

#Transaction count by occupation
select CustomerOccupation, count(TransactionID)as transaction_count
from bank_transaction_clean
group by CustomerOccupation
order by transaction_count desc;

#Transaction value by occupation
select CustomerOccupation, round(sum(TransactionAmount),2) as transaction_value
from bank_transaction_clean
group by CustomerOccupation
order by transaction_value desc;

#Average account balance by occupation
select CustomerOccupation, round(avg(AccountBalance),2) as avg_acct_balance
from bank_transaction_clean
group by CustomerOccupation
order by avg_acct_balance desc;

#Age groups and transaction behaviour
select 
		case 
        when CustomerAge < 25 then '18-24'
        when CustomerAge between 25 and 34 then '25-34'
        when CustomerAge between 35 and 44 then '35-44'
		when CustomerAge between 45 and 54 then '45-54'
        else '55+'
        end as Age_Groups,
        count(*) as transaction_count,
        round(sum(TransactionAmount),2) as total_transaction_amt,
        round(avg(TransactionAmount),2) as avg_transaction_amt
        from bank_transaction_clean
        group by Age_Groups
        order by transaction_count desc;
	

#Most active accounts
select AccountID, count(*) as transaction_acct
from bank_transaction_clean
group by AccountID
order by transaction_acct desc ;

#Highest-value accounts
select  AccountID, round(sum(TransactionAmount),2) as total_transaction_value
from bank_transaction_clean
group by  AccountID
order by total_transaction_value desc;

## Channel analysis
# total transactional amount each channel has generated
select `Channel`, round(sum(TransactionAmount),2)as total_transactional_amount_generated
from bank_transaction_clean
group by `Channel`;

# which channel has used what transaction type to generate the highest transaction amount
select `Channel`,TransactionType ,max(TransactionAmount) as max_transaction_amount
from bank_transaction_clean
group by `Channel`, TransactionType
order by max_transaction_amount desc ;

# find the average transaction amount generated by each channels
select `Channel`, round(avg(TransactionAmount),2) as average_transaction_amount_generated
from bank_transaction_clean
group by `Channel`;

## location analysis
# which location ppl has generated highest transaction amount
select Location, round(sum(TransactionAmount),2) as highest_transaction_amount
from bank_transaction_clean
group by Location
order by highest_transaction_amount desc;

# which location has generated the most transactions
select Location, count(TransactionID) as most_transactions_generated
from bank_transaction_clean
group by Location
order by most_transactions_generated desc;

##Transaction behaviour

#Transaction type distribution
select TransactionType, count(*) as transaction_count
from bank_transaction_clean
group by TransactionType 
order by transaction_count desc;

#Average amount by transaction type
select TransactionType, round(avg(TransactionAmount),2) as avg_transaction_amt
from bank_transaction_clean
group by TransactionType
order by avg_transaction_amt desc;


#Total amount by transaction type
select TransactionType, round(sum(TransactionAmount),2) as total_transaction_amt
from bank_transaction_clean
group by TransactionType
order by total_transaction_amt desc;

#Transaction duration by transaction type
select TransactionType, round(avg(TransactionDuration),2) as avg_transaction_duration
from bank_transaction_clean
group by TransactionType
order by avg_transaction_duration desc;

##Risk / unusual behaviour
#High-value transactions
select TransactionID, AccountID, TransactionAmount
from bank_transaction_clean
order by TransactionAmount desc
limit 10;

#High login attempts
select LoginAttempts, count(*) as login_attempts
from bank_transaction_clean
group by LoginAttempts
order by login_attempts desc;

#Long transaction durations
select TransactionID, AccountID, TransactionDuration
from bank_transaction_clean
order by TransactionDuration desc
limit 10;

#High-value transactions with high login attempts
select TransactionID, AccountID, TransactionAmount, LoginAttempts
from bank_transaction_clean
where TransactionAmount > (
select round(avg(TransactionAmount),2) as avg_transaction_amt
from bank_transaction_clean)
and LoginAttempts > (
select round(avg(LoginAttempts),2) as avg_login_attempt
from bank_transaction_clean)
order by TransactionAmount desc;

#Accounts with unusually frequent transactions
select AccountID, count(*) as transaction_count
from bank_transaction_clean
group by AccountID
having count(*) > (
				   select avg(transaction_count) 
                   from (
						select AccountID, count(*) as transaction_count
						from bank_transaction_clean
						group by AccountID)x)
						order by transaction_count desc;